"""staff.username *.email *.phone unique

Revision ID: 0e1b318679d7
Revises: f42e1599e402
Create Date: 2026-01-12 15:17:43.758041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e1b318679d7'
down_revision: Union[str, Sequence[str], None] = 'f42e1599e402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'staff', ['email'])
    op.create_unique_constraint(None, 'staff', ['phone'])
    op.create_unique_constraint(None, 'staff', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('staff_email_key', 'staff', type_='unique')
    op.drop_constraint('staff_phone_key', 'staff', type_='unique')
    op.drop_constraint('staff_username_key', 'staff', type_='unique')
    # ### end Alembic commands ###
