"""add_cascade_delete_refreshtoken

Revision ID: 5471171f8e4e
Revises: 5203c2874e58
Create Date: 2026-05-28 11:35:09.096418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5471171f8e4e'
down_revision: Union[str, Sequence[str], None] = '5203c2874e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refreshtoken_staff_id_fkey'), 'refreshtoken', type_='foreignkey')
    op.create_foreign_key(None, 'refreshtoken', 'staff', ['staff_id'], ['staff_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refreshtoken', type_='foreignkey')
    op.create_foreign_key(op.f('refreshtoken_staff_id_fkey'), 'refreshtoken', 'staff', ['staff_id'], ['staff_id'])
    # ### end Alembic commands ###
