"""passport unique

Revision ID: f42e1599e402
Revises: 9fbff3784045
Create Date: 2026-01-12 15:07:47.798631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f42e1599e402'
down_revision: Union[str, Sequence[str], None] = '9fbff3784045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client', ['passport'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_passport_key', 'client', type_='unique')
    # ### end Alembic commands ###
